name: tayloraldridge
favicon: null
layout_spectrum: 0.4704354787245393
typography_spectrum: 0.3530713461805135
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cde4ea'
    - '#a81e1e'
    - '#121757'
    - '#337fb0'
    - '#8fbcd3'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.3077350847888738
purpose: []
